language: node_js
node_js:
  - stable

install:
  - npm i -g typescript typings
  - npm install

before_script:
  - npm run build

script:
  - npm test

deploy:
  skip_cleanup: true
  provider: npm

  email: julien.sarazin@me.com
  api_key:
    secure: Ewiy7c/M9d2MRSB+cU6qzxnNVYAup2Jmm/E/w4jvF/P6tTswKfGMCH6Qq8+COoigQnoj7l6P4L1/rcixjSYx+cZCX0jDDal08vtrxe5AeQg1hKi4j8N7ra8Jn3f6OSK2ZjVYHISNAQIpSk6w5OwWKhzw8c1Q9j/tO8N+9iliJ4/YJrI/Sdv0lDKrERAxUeCVFpLFF2C0M5+jKHz39jaBcMvYEA98i7R3eMJpqJIs2bfm2vxkrjZTMlGwUmAKPBpl1gTGhPlCAvhoo9ErRDGkWYcYR8LrWx1u3lxAOOLV3D7oQNnh2E4UPUPTavPvQOabT78RB7QIHZEfeA6mnb26/kS3MSV7rKEZLtAxRqqOnLzUuro3hB1TbeyRXCojc0kVJjZ5sgcuZYSxzgMEKvmYc81Rm+UAY1rdhW53FUOC8/Yvw96+JVqdre41anuIDvvZKI88IHOr5qOWRp7uJHbvtFdEfFCZwxnfLBozinQJQJHngIbxfMsnTSQrHtGPyUIY/7haHu5I8D/gMleBj8qu2+0sLSjGDYS37J+KP3ryu4k3dw1XHbB1mrH6sQABc/jPdiLFarMC/dVCU00LZn2bBHWEpn38NB1P8TAZDib/K6YIMpjpzkanlyNAMw4TPGAWk4owBU09s/AEm6zuG1yvdZKepdHwS1/lwbktP/8A80o=
  on:
    tags: true
    repo: implicity-healthcare/nest-consul
